name: Frends.Smtp.SendEmail Release

on:
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.Smtp.SendEmail
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
      